import type { FaceProps, ExpressionPreset } from "./types";
import { DEFAULT_FACE } from "./types";

export const EXPRESSION_PRESETS: Record<ExpressionPreset, Partial<FaceProps>> = {
  neutral: {
    expression: "neutral",
    eyeStyle: "dot",
    mouthStyle: "line",
    mouthCurve: 0,
    eyebrowStyle: "line",
    eyebrowTilt: 0,
  },
  happy: {
    expression: "happy",
    eyeStyle: "dot",
    mouthStyle: "smile",
    mouthCurve: 0.8,
    mouthSize: 1.2,
    eyebrowStyle: "arc",
    eyebrowTilt: 0.2,
  },
  smiles: {
    expression: "smiles",
    eyeStyle: "dot",
    mouthStyle: "smile",
    mouthCurve: 1.0,
    mouthSize: 1.35,
    eyebrowStyle: "arc",
    eyebrowTilt: 0.25,
  },
  joy: {
    expression: "joy",
    eyeStyle: "wide",
    eyeSize: 1.25,
    mouthStyle: "open",
    mouthSize: 1.25,
    mouthEffect: "talk",
    mouthTalkAmount: 0.35,
    eyebrowStyle: "arc",
    eyebrowTilt: 0.35,
  },
  sad: {
    expression: "sad",
    eyeStyle: "dot",
    mouthStyle: "frown",
    mouthCurve: -0.6,
    eyeOffsetY: -0.05,
    eyebrowStyle: "sad",
    eyebrowTilt: -0.3,
  },
  angry: {
    expression: "angry",
    eyeStyle: "angry",
    mouthStyle: "frown",
    mouthCurve: -0.4,
    mouthSize: 0.8,
    eyebrowStyle: "angry",
    eyebrowTilt: 0.8,
  },
  fear: {
    expression: "fear",
    eyeStyle: "wide",
    eyeSize: 1.55,
    mouthStyle: "o",
    mouthSize: 1.15,
    mouthEffect: "talk",
    mouthTalkAmount: 0.6,
    eyebrowStyle: "sad",
    eyebrowTilt: -0.55,
  },
  thinking: {
    expression: "thinking",
    eyeStyle: "circle",
    eyeSize: 0.95,
    mouthStyle: "line",
    mouthCurve: -0.1,
    mouthOffsetY: 0.2,
    eyebrowStyle: "line",
    eyebrowTilt: 0.35,
  },
  worry: {
    expression: "worry",
    eyeStyle: "circle",
    mouthStyle: "wavy",
    mouthCurve: -0.35,
    eyeSize: 0.9,
    eyebrowStyle: "sad",
    eyebrowTilt: -0.45,
  },
  surprised: {
    expression: "surprised",
    eyeStyle: "wide",
    mouthStyle: "o",
    eyeSize: 1.4,
    mouthSize: 1.3,
    mouthEffect: "talk",
    mouthTalkAmount: 0.5,
    eyebrowStyle: "line",
    eyebrowTilt: 0.1,
  },
  worried: {
    expression: "worried",
    eyeStyle: "circle",
    mouthStyle: "wavy",
    mouthCurve: -0.3,
    eyeSize: 0.9,
    eyebrowStyle: "sad",
    eyebrowTilt: -0.4,
  },
  releive: {
    expression: "releive",
    eyeStyle: "closed",
    mouthStyle: "smile",
    mouthCurve: 0.55,
    mouthSize: 1.05,
    eyebrowStyle: "arc",
    eyebrowTilt: -0.1,
  },
  content: {
    expression: "content",
    eyeStyle: "dot",
    mouthStyle: "small-smile",
    mouthCurve: 0.35,
    eyebrowStyle: "line",
    eyebrowTilt: 0.05,
  },
  bored: {
    expression: "bored",
    eyeStyle: "closed",
    mouthStyle: "line",
    mouthCurve: -0.1,
    mouthOffsetY: 0.17,
    eyebrowStyle: "line",
    eyebrowTilt: -0.1,
  },
  meh: {
    expression: "meh",
    eyeStyle: "dot",
    eyeSize: 0.9,
    mouthStyle: "line",
    mouthCurve: 0,
    eyebrowStyle: "line",
    eyebrowTilt: -0.2,
  },
  tongueOut: {
    expression: "tongueOut",
    eyeStyle: "wink",
    mouthStyle: "open",
    mouthSize: 1.1,
    mouthEffect: "talk",
    mouthTalkAmount: 0.3,
    eyebrowStyle: "line",
    eyebrowTilt: 0.2,
  },
  sleeping: {
    expression: "sleeping",
    eyeStyle: "closed",
    mouthStyle: "small-smile",
    mouthCurve: 0.15,
    eyebrowStyle: "none",
  },
  tired: {
    expression: "tired",
    eyeStyle: "closed",
    mouthStyle: "frown",
    mouthCurve: -0.2,
    eyebrowStyle: "sad",
    eyebrowTilt: -0.2,
  },
  kiss: {
    expression: "kiss",
    eyeStyle: "closed",
    mouthStyle: "o",
    mouthSize: 0.85,
    eyebrowStyle: "arc",
    eyebrowTilt: 0.1,
  },
  flirt: {
    expression: "flirt",
    eyeStyle: "wink",
    mouthStyle: "small-smile",
    mouthCurve: 0.55,
    mouthOffsetY: 0.18,
    eyebrowStyle: "line",
    eyebrowTilt: 0.35,
  },
  smug: {
    expression: "smug",
    eyeStyle: "dot",
    mouthStyle: "small-smile",
    mouthCurve: 0.5,
    mouthOffsetY: 0.18,
    eyebrowStyle: "line",
    eyebrowTilt: 0.45,
  },
  scared: {
    expression: "scared",
    eyeStyle: "wide",
    mouthStyle: "wavy",
    eyeSize: 1.5,
    mouthSize: 1.1,
    mouthEffect: "talk",
    mouthTalkAmount: 0.7,
    eyebrowStyle: "sad",
    eyebrowTilt: -0.6,
  },
  dead: {
    expression: "dead",
    eyeStyle: "closed",
    mouthStyle: "line",
    mouthCurve: 0,
    eyeSize: 1.2,
    eyebrowStyle: "none",
  },
};

export function applyPreset(preset: ExpressionPreset): FaceProps {
  return { ...DEFAULT_FACE, ...EXPRESSION_PRESETS[preset] };
}
